"""新增  Post 欄位(is_private)

Revision ID: 42f234f987e1
Revises: cbf67e220ff1
Create Date: 2021-10-26 15:47:15.122441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f234f987e1'
down_revision = 'cbf67e220ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_private')
    # ### end Alembic commands ###
