"""新增  User 欄位

Revision ID: 447f0f398fb9
Revises: bbb2377026df
Create Date: 2021-10-23 14:29:03.276176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447f0f398fb9'
down_revision = 'bbb2377026df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
